import React from 'react';
import Head from 'next/head';

function Layout(props) {
    return (
        <div style={{
            position: "relative",
            height: "100vh",
            paddingLeft: "1rem",
            backgroundColor: "#22146C",
            display: "flex", justifyContent: "center"
        }}>
            <Head>
                <title>Covid-19 Worldview</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main style={{ marginLeft: '-6rem' }}>
                {props.children}
            </main>
        </div>
    );
}

export default Layout;